// This file is generated by ./scripts/generate-migrations.ts.
// Do not edit it manually.

export const DRIZZLE_MIGRATIONS = [
	{
		idx: 0,
		tag: "0000_strong_reavers",
		sql: "CREATE TABLE `document_records` (\n\t`integration_id` text NOT NULL,\n\t`connector_id` text NOT NULL,\n\t`source_id` text NOT NULL,\n\t`entity_type` text NOT NULL,\n\t`relative_path` text NOT NULL,\n\t`source_hash` text NOT NULL,\n\t`render_version` text NOT NULL,\n\t`snapshot_hash` text NOT NULL,\n\t`source_updated_at` text,\n\t`last_rendered_at` text,\n\tPRIMARY KEY(`integration_id`, `source_id`)\n);\n--> statement-breakpoint\nCREATE TABLE `integration_state` (\n\t`integration_id` text PRIMARY KEY NOT NULL,\n\t`cursor_value` text,\n\t`last_sync_at` text\n);\n--> statement-breakpoint\nCREATE TABLE `source_snapshots` (\n\t`integration_id` text NOT NULL,\n\t`connector_id` text NOT NULL,\n\t`source_id` text NOT NULL,\n\t`snapshot_hash` text NOT NULL,\n\t`snapshot_schema_version` text NOT NULL,\n\t`payload_json` text NOT NULL,\n\tPRIMARY KEY(`integration_id`, `source_id`)\n);\n",
	},
] as const;
