export { createSyncdownApp } from "./app.js";
export {
	createStdIo,
	ensureAppDirectories,
	ensureConfig,
	readConfig,
	resolveAppPaths,
	validateManagedOutputDirectory,
	writeConfig,
} from "./config.js";
export {
	createDefaultConfig,
	DEFAULT_APPLE_NOTES_CONNECTION_ID,
	DEFAULT_GOOGLE_CONNECTION_ID,
	DEFAULT_GOOGLE_OAUTH_APP_ID,
	DEFAULT_NOTION_OAUTH_APP_ID,
	DEFAULT_NOTION_OAUTH_CONNECTION_ID,
	DEFAULT_NOTION_TOKEN_CONNECTION_ID,
	findConnection,
	findIntegration,
	findOAuthApp,
	getDefaultConnection,
	getDefaultConnectionId,
	getDefaultIntegration,
	isAppleNotesIntegration,
	isCalendarIntegration,
	isGmailIntegration,
	isGoogleAccountConnection,
	isNotionIntegration,
	isNotionOAuthConnection,
	listIntegrationsForConnector,
} from "./config-model.js";
export type {
	GoogleAccessTokenProvider,
	GoogleOAuthCredentials,
	GoogleTokenResponse,
} from "./google-auth.js";
export {
	assertGoogleGrantedScopes,
	buildGoogleAuthUrl,
	collectGoogleProviderScopes,
	createGoogleAccessTokenProvider,
	exchangeGoogleAuthCode,
	fetchGoogleGrantedScopes,
	GOOGLE_AUTH_URL,
	GOOGLE_SECRET_NAMES,
	GOOGLE_TOKEN_URL,
	getGoogleAuthConnectors,
	getGoogleConnectionSecretNames,
	getGoogleOAuthAppSecretNames,
	getRequiredGoogleScopes,
	hasGoogleConnectionCredentials,
	hasGoogleCredentials,
	isGoogleProviderAuth,
	normalizeGoogleScopes,
	readGoogleConnectionCredentials,
	readGoogleCredentials,
	refreshGoogleAccessToken,
} from "./google-auth.js";
export type {
	NotionOAuthCredentials,
	NotionOAuthTokenExchangeResult,
} from "./notion-auth.js";
export {
	buildNotionAuthUrl,
	exchangeNotionAuthCode,
	getNotionOAuthAppSecretNames,
	getNotionOAuthConnectionSecretNames,
	hasNotionOAuthConnectionCredentials,
	NOTION_AUTH_URL,
	NOTION_SETUP_URL,
	NOTION_TOKEN_URL,
	readNotionOAuthConnectionCredentials,
	refreshNotionAccessToken,
} from "./notion-auth.js";
export { defineConnectorPlugin } from "./plugin.js";
export type {
	AppIo,
	AppleNotesIntegrationConfig,
	AppleNotesIntegrationSettings,
	AppleNotesLocalConnectionConfig,
	ApplyUpdateResult,
	AppPaths,
	AppSnapshot,
	CalendarIntegrationConfig,
	CalendarIntegrationSettings,
	ConnectionConfig,
	ConnectionKind,
	ConnectionSummary,
	Connector,
	ConnectorCliAlias,
	ConnectorCliAliasContext,
	ConnectorConfigFieldDescriptor,
	ConnectorConfigFieldType,
	ConnectorConfigOption,
	ConnectorDefinitionSummary,
	ConnectorId,
	ConnectorManifest,
	ConnectorOptionLoader,
	ConnectorOptionLoaderContext,
	ConnectorPlugin,
	ConnectorRenderHooks,
	ConnectorSyncRequest,
	ConnectorSyncResult,
	DocumentSink,
	GenericConnectionConfig,
	GenericIntegrationConfig,
	GenericTokenResolvedAuth,
	GmailIntegrationConfig,
	GmailIntegrationSettings,
	GmailSyncFilter,
	GoogleResolvedAuth,
	HealthCheck,
	IntegrationConfig,
	IntegrationRuntimeProgress,
	IntegrationRuntimeSnapshot,
	IntegrationSummary,
	MarkdownRenderer,
	NotionIntegrationConfig,
	NotionIntegrationSettings,
	NotionOAuthConnectionConfig,
	NotionOAuthResolvedAuth,
	NotionResolvedAuth,
	OAuthAppConfig,
	ProviderId,
	ProviderOAuthSetupMethodDescriptor,
	RenderedDocument,
	ResolvedConnectionAuth,
	RunNowOptions,
	RunOptions,
	SecretsStore,
	SelfUpdater,
	SetupMethodDescriptor,
	SinkWriteRequest,
	SinkWriteResult,
	SourceMetadata,
	SourceRecord,
	SourceSnapshot,
	StateStore,
	StoredSourceSnapshot,
	SyncdownApp,
	SyncdownConfig,
	SyncdownServices,
	SyncIntervalPreset,
	SyncLogEntry,
	SyncRunTarget,
	SyncRuntimeEvent,
	SyncRuntimeSnapshot,
	SyncSession,
	TokenSetupMethodDescriptor,
	UpdateStatus,
	WatchStrategy,
} from "./types.js";
export { EXIT_CODES } from "./types.js";
