import path from "node:path";

interface JournalEntry {
	idx: number;
	tag: string;
}

interface JournalFile {
	entries: JournalEntry[];
}

const packageRoot = path.resolve(import.meta.dir, "..");
const drizzleDir = path.join(packageRoot, "drizzle");
const journalPath = path.join(drizzleDir, "meta", "_journal.json");
const outputPath = path.join(packageRoot, "src", "generated-migrations.ts");

function renderGeneratedSource(
	entries: Array<{ idx: number; tag: string; sql: string }>,
): string {
	return [
		"// This file is generated by ./scripts/generate-migrations.ts.",
		"// Do not edit it manually.",
		"",
		"export const DRIZZLE_MIGRATIONS = [",
		...entries.map(
			(entry) =>
				`  {\n    idx: ${entry.idx},\n    tag: ${JSON.stringify(entry.tag)},\n    sql: ${JSON.stringify(entry.sql)}\n  },`,
		),
		"] as const;",
		"",
	].join("\n");
}

const journal = JSON.parse(await Bun.file(journalPath).text()) as JournalFile;
const migrations = await Promise.all(
	[...journal.entries]
		.sort((left, right) => left.idx - right.idx)
		.map(async (entry) => ({
			idx: entry.idx,
			tag: entry.tag,
			sql: await Bun.file(path.join(drizzleDir, `${entry.tag}.sql`)).text(),
		})),
);

await Bun.write(outputPath, renderGeneratedSource(migrations));
